### ISSUE TITLE
Precompilation error with v0.25.2

### ISSUE THREAD

**Issue by ElOceanografo** [JuliaEarth/GeoStats.jl#187] opened 2021-06-23 19:29 UTC
I'm getting a precompilation error when `using GeoStats` after installing v0.25.2:
```
julia> using GeoStats
[ Info: Precompiling GeoStats [dcc97b0b-8ce5-5539-9008-bb190f959ef6]
ERROR: LoadError: MethodError: no method matching names(::Base.Broadcast.BroadcastFunction{UnionAll})
Closest candidates are:
  names(::Module; all, imported) at reflection.jl:98
Stacktrace:
 [1] top-level scope
   @ ~\.julia\packages\GeoStats\bAaZd\src\GeoStats.jl:11
 [2] include
   @ .\Base.jl:386 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1213
 [4] top-level scope
   @ none:1
 [5] eval
   @ .\boot.jl:360 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude .\client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at C:\Users\sam.urmy\.julia\packages\GeoStats\bAaZd\src\GeoStats.jl:5
ERROR: Failed to precompile GeoStats [dcc97b0b-8ce5-5539-9008-bb190f959ef6] to C:\Users\sam.urmy\.julia\compiled\v1.6\GeoStats\jl_5814.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base .\loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:901
```
I'm using Julia 1.6.0 on Windows 10 Enterprise, and my environment is the following:
```
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.1.1
  [1313f7d8] DataFramesMeta v0.7.1
  [dcc97b0b] GeoStats v0.25.2
  [0ef565a4] Geodesy v1.0.1
  [91a5bcdd] Plots v1.16.5
  [f3b207a7] StatsPlots v0.14.23
```
It works fine if I downgrade to v0.25.1.   Maybe something to do with [changes](https://github.com/JuliaEarth/GeoStats.jl/compare/v0.25.1...v0.25.2) to the `@reexports` of related packages?

**Comment by juliohm** [comment] 2021-06-23 19:37
That is strange. Can you try to create a fresh temporary environment with
just the package installed and see if the issue is there ? I am using
v0.25.2 without problems in other environments.

**Comment by ElOceanografo** [comment] 2021-06-23 19:48
Just tried it in a clean environment, the same problem occurs:
```
(@v1.6) pkg> activate .
  Activating new environment at `C:\Users\sam.urmy\Work\tmp\Project.toml`

(tmp) pkg> add GeoStats
    Updating registry at `C:\Users\sam.urmy\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `C:\Users\sam.urmy\Work\tmp\Project.toml`
  [dcc97b0b] + GeoStats v0.25.2
    Updating `C:\Users\sam.urmy\Work\tmp\Manifest.toml`
  [621f4979] + AbstractFFTs v1.0.1
  [79e6a3ab] + Adapt v3.3.1
  [dce04be8] + ArgCheck v2.1.0
  [4fba245c] + ArrayInterface v3.1.17
  [77b51b56] + AverageShiftedHistograms v0.8.6
  [198e06fe] + BangBang v0.3.31
  [9718e550] + Baselet v0.1.1
  [336ed68f] + CSV v0.8.5
  [324d7699] + CategoricalArrays v0.10.0
  [d360d2e6] + ChainRulesCore v0.10.9
  [7a955b69] + CircularArrays v1.2.0
  [861a8166] + Combinatorics v1.0.2
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v3.31.0
  [a33af91c] + CompositionsBase v0.1.0
  [187b0558] + ConstructionBase v1.3.0
  [adafc99b] + CpuId v0.3.0
  [a8cc5b0e] + Crayons v4.0.4
  [9a962f9c] + DataAPI v1.6.0
  [864edb3b] + DataStructures v0.18.9
  [e2d170a0] + DataValueInterfaces v1.0.0
  [244e2a9f] + DefineSingletons v0.1.1
  [ab46fb84] + DensityRatioEstimation v0.4.3
  [85a47980] + Dictionaries v0.3.8
  [163ba53b] + DiffResults v1.0.3
  [b552c78f] + DiffRules v1.0.2
  [b4f34e82] + Distances v0.10.3
  [31c24e10] + Distributions v0.25.5
  [ffbed154] + DocStringExtensions v0.8.5
  [7a1cc6ca] + FFTW v1.4.3
  [1a297f60] + FillArrays v0.11.7
  [6a86dc24] + FiniteDiff v2.8.0
  [f6369f11] + ForwardDiff v0.10.18
  [7472b188] + GeoClustering v0.1.5
  [a4aa24f8] + GeoEstimation v0.7.2
  [90c4468e] + GeoLearning v0.1.4
  [220efe8a] + GeoSimulation v0.3.6
  [dcc97b0b] + GeoStats v0.25.2
  [323cb8eb] + GeoStatsBase v0.21.8
  [615f187c] + IfElse v0.1.0
  [313cdc1a] + Indexing v1.1.1
  [22cec73e] + InitialValues v0.2.10
  [c8e1da08] + IterTools v1.3.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [692b3bcd] + JLLWrappers v1.3.0
  [682c06a0] + JSON v0.21.1
  [d293930c] + KrigingEstimators v0.7.5
  [7f8f8fb0] + LearnBase v0.4.1
  [d3d80556] + LineSearches v7.1.1
  [2ab3a3ac] + LogExpFunctions v0.2.4
  [30fc2ffe] + LossFunctions v0.7.2
  [e80e1ace] + MLJModelInterface v1.1.0
  [1914dd2f] + MacroTools v0.5.6
  [eacbb407] + Meshes v0.16.10
  [128add7d] + MicroCollections v0.1.0
  [e1d29d7a] + Missings v1.0.0
  [d41bc354] + NLSolversBase v7.8.0
  [77ba4419] + NaNMath v0.3.5
  [b8a86587] + NearestNeighbors v0.4.9
  [6fe1bfb0] + OffsetArrays v1.10.0
  [429524aa] + Optim v1.3.0
  [bac558e1] + OrderedCollections v1.4.1
  [90014a1f] + PDMats v0.11.1
  [d96e819e] + Parameters v0.12.2
  [69de0a69] + Parsers v1.1.0
  [e61b41b6] + PointPatterns v0.3.8
  [2dfb63ee] + PooledArrays v1.2.1
  [85a6dd25] + PositiveFactorizations v0.2.4
  [21216c6a] + Preferences v1.2.2
  [1fd47b50] + QuadGK v2.4.1
  [3cdcf5f2] + RecipesBase v1.1.1
  [189a3867] + Reexport v1.1.0
  [74f56ac7] + ReferenceFrameRotations v1.0.0
  [ae029012] + Requires v1.1.3
  [79098fc4] + Rmath v0.7.0
  [321657f4] + ScientificTypes v1.1.2
  [91c51154] + SentinelArrays v1.3.3
  [efcf1570] + Setfield v0.7.0
  [699a6c99] + SimpleTraits v0.9.3
  [a2af1166] + SortingAlgorithms v1.0.0
  [276daf66] + SpecialFunctions v1.5.1
  [03a91e81] + SplitApplyCombine v1.1.4
  [171d559e] + SplittablesBase v0.1.13
  [aedffcd0] + Static v0.2.5
  [90137ffa] + StaticArrays v1.2.4
  [64bff920] + StatisticalTraits v1.1.0
  [82ae8749] + StatsAPI v1.0.0
  [2913bbd2] + StatsBase v0.33.8
  [4c63d2b9] + StatsFuns v0.9.8
  [856f2bd8] + StructTypes v1.7.2
  [ab02a1b2] + TableOperations v1.0.0
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.4.4
  [28d57a85] + Transducers v0.4.65
  [9d95f2ec] + TypedTables v1.3.0
  [3a884ed6] + UnPack v1.0.2
  [b8865327] + UnicodePlots v1.3.0
  [04a0146e] + Variography v0.12.8
  [700de1a5] + ZygoteRules v0.2.1
  [f5851436] + FFTW_jll v3.3.9+7
  [1d5cc7b8] + IntelOpenMP_jll v2018.0.3+2
  [856f044c] + MKL_jll v2021.1.1+1
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [f50d1b31] + Rmath_jll v0.3.0+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
Precompiling project...
  Progress [========================================>]  1/1
  ✗ GeoStats
0 dependencies successfully precompiled in 8 seconds (107 already precompiled)
1 dependency errored

(tmp) pkg> 

julia> using GeoStats
[ Info: Precompiling GeoStats [dcc97b0b-8ce5-5539-9008-bb190f959ef6]
ERROR: LoadError: MethodError: no method matching names(::Base.Broadcast.BroadcastFunction{UnionAll})
Closest candidates are:
  names(::Module; all, imported) at reflection.jl:98
Stacktrace:
 [1] top-level scope
   @ ~\.julia\packages\GeoStats\bAaZd\src\GeoStats.jl:11
 [2] include
   @ .\Base.jl:386 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1213
 [4] top-level scope
   @ none:1
 [5] eval
   @ .\boot.jl:360 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude .\client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at C:\Users\sam.urmy\.julia\packages\GeoStats\bAaZd\src\GeoStats.jl:5
ERROR: Failed to precompile GeoStats [dcc97b0b-8ce5-5539-9008-bb190f959ef6] to C:\Users\sam.urmy\.julia\compiled\v1.6\GeoStats\jl_249C.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base .\loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:901
```

**Comment by juliohm** [comment] 2021-06-23 20:02
That is super strange. I'll try to take a look when I get home. I don't
remember any names function in the packages.

**Comment by juliohm** [comment] 2021-06-23 21:18
I have just tried installing in a fresh environment and everything went well:

```julia
(@v1.6) pkg> activate --temp
  Activating new environment at `/tmp/jl_nohmPp/Project.toml`

(jl_nohmPp) pkg> add GeoStats
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
   Installed ChainRulesCore ─ v0.10.9
   Installed TypedTables ──── v1.3.0
   Installed Tables ───────── v1.4.4
    Updating `/tmp/jl_nohmPp/Project.toml`
  [dcc97b0b] + GeoStats v0.25.2
    Updating `/tmp/jl_nohmPp/Manifest.toml`
  [621f4979] + AbstractFFTs v1.0.1
  [79e6a3ab] + Adapt v3.3.1
  [dce04be8] + ArgCheck v2.1.0
  [4fba245c] + ArrayInterface v3.1.17
  [77b51b56] + AverageShiftedHistograms v0.8.6
  [198e06fe] + BangBang v0.3.31
  [9718e550] + Baselet v0.1.1
  [336ed68f] + CSV v0.8.5
  [324d7699] + CategoricalArrays v0.10.0
  [d360d2e6] + ChainRulesCore v0.10.9
  [7a955b69] + CircularArrays v1.2.0
  [861a8166] + Combinatorics v1.0.2
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v3.31.0
  [a33af91c] + CompositionsBase v0.1.0
  [187b0558] + ConstructionBase v1.3.0
  [adafc99b] + CpuId v0.3.0
  [a8cc5b0e] + Crayons v4.0.4
  [9a962f9c] + DataAPI v1.6.0
  [864edb3b] + DataStructures v0.18.9
  [e2d170a0] + DataValueInterfaces v1.0.0
  [244e2a9f] + DefineSingletons v0.1.1
  [ab46fb84] + DensityRatioEstimation v0.4.3
  [85a47980] + Dictionaries v0.3.8
  [163ba53b] + DiffResults v1.0.3
  [b552c78f] + DiffRules v1.0.2
  [b4f34e82] + Distances v0.10.3
  [31c24e10] + Distributions v0.25.5
  [ffbed154] + DocStringExtensions v0.8.5
  [7a1cc6ca] + FFTW v1.4.3
  [1a297f60] + FillArrays v0.11.7
  [6a86dc24] + FiniteDiff v2.8.0
  [f6369f11] + ForwardDiff v0.10.18
  [7472b188] + GeoClustering v0.1.5
  [a4aa24f8] + GeoEstimation v0.7.2
  [90c4468e] + GeoLearning v0.1.4
  [220efe8a] + GeoSimulation v0.3.6
  [dcc97b0b] + GeoStats v0.25.2
  [323cb8eb] + GeoStatsBase v0.21.8
  [615f187c] + IfElse v0.1.0
  [313cdc1a] + Indexing v1.1.1
  [22cec73e] + InitialValues v0.2.10
  [c8e1da08] + IterTools v1.3.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [692b3bcd] + JLLWrappers v1.3.0
  [682c06a0] + JSON v0.21.1
  [d293930c] + KrigingEstimators v0.7.5
  [7f8f8fb0] + LearnBase v0.4.1
  [d3d80556] + LineSearches v7.1.1
  [2ab3a3ac] + LogExpFunctions v0.2.4
  [30fc2ffe] + LossFunctions v0.7.2
  [e80e1ace] + MLJModelInterface v1.1.0
  [1914dd2f] + MacroTools v0.5.6
  [eacbb407] + Meshes v0.16.10
  [128add7d] + MicroCollections v0.1.0
  [e1d29d7a] + Missings v1.0.0
  [d41bc354] + NLSolversBase v7.8.0
  [77ba4419] + NaNMath v0.3.5
  [b8a86587] + NearestNeighbors v0.4.9
  [6fe1bfb0] + OffsetArrays v1.10.0
  [429524aa] + Optim v1.3.0
  [bac558e1] + OrderedCollections v1.4.1
  [90014a1f] + PDMats v0.11.1
  [d96e819e] + Parameters v0.12.2
  [69de0a69] + Parsers v1.1.0
  [e61b41b6] + PointPatterns v0.3.8
  [2dfb63ee] + PooledArrays v1.2.1
  [85a6dd25] + PositiveFactorizations v0.2.4
  [21216c6a] + Preferences v1.2.2
  [1fd47b50] + QuadGK v2.4.1
  [3cdcf5f2] + RecipesBase v1.1.1
  [189a3867] + Reexport v1.1.0
  [74f56ac7] + ReferenceFrameRotations v1.0.0
  [ae029012] + Requires v1.1.3
  [79098fc4] + Rmath v0.7.0
  [321657f4] + ScientificTypes v1.1.2
  [91c51154] + SentinelArrays v1.3.3
  [efcf1570] + Setfield v0.7.0
  [699a6c99] + SimpleTraits v0.9.3
  [a2af1166] + SortingAlgorithms v1.0.0
  [276daf66] + SpecialFunctions v1.5.1
  [03a91e81] + SplitApplyCombine v1.1.4
  [171d559e] + SplittablesBase v0.1.13
  [aedffcd0] + Static v0.2.5
  [90137ffa] + StaticArrays v1.2.4
  [64bff920] + StatisticalTraits v1.1.0
  [82ae8749] + StatsAPI v1.0.0
  [2913bbd2] + StatsBase v0.33.8
  [4c63d2b9] + StatsFuns v0.9.8
  [856f2bd8] + StructTypes v1.7.2
  [ab02a1b2] + TableOperations v1.0.0
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.4.4
  [28d57a85] + Transducers v0.4.65
  [9d95f2ec] + TypedTables v1.3.0
  [3a884ed6] + UnPack v1.0.2
  [b8865327] + UnicodePlots v1.3.0
  [04a0146e] + Variography v0.12.8
  [700de1a5] + ZygoteRules v0.2.1
  [f5851436] + FFTW_jll v3.3.9+7
  [1d5cc7b8] + IntelOpenMP_jll v2018.0.3+2
  [856f044c] + MKL_jll v2021.1.1+1
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [f50d1b31] + Rmath_jll v0.3.0+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
  Progress [========================================>]  26/26
26 dependencies successfully precompiled in 27 seconds (82 already precompiled)

(jl_nohmPp) pkg> st
      Status `/tmp/jl_nohmPp/Project.toml`
  [dcc97b0b] GeoStats v0.25.2

julia> using GeoStats

julia>
```

Perhaps this issue is OS-dependent? Here is my versioninfo()

```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by juliohm** [comment] 2021-06-24 12:15
@ElOceanografo can you confirm your Julia binary? By any chance you are using one of those JuliaPro binaries?

**Comment by juliohm** [comment] 2021-06-25 10:50
Closing as invalid. Let me know if the problem persists. Notice that the GitHub bot tests against all platforms and the Windows build is successful.

**Closed by juliohm** 2021-06-25 10:50 UTC
Labels: invalid
