### ISSUE TITLE
Error in SGS with multiple processes

### ISSUE THREAD

**Issue by conordoherty** [JuliaEarth/GeoStats.jl#267] opened 2023-06-06 20:39 UTC
I'm trying to generate multiple realizations in parallel using SGS. To do this, I run the following:

using Distributed
addprocs(10)

[ lots of stuff ]

solver = SGS([...])
problem = SimulationProblem([...], 10)
s = solve(problem, solver, procs=Vector(2:11)) # version 1
[ or ]
s = solve(problem, solver, procs=Vector(1:11)) # version 2
When I do the first version (Vector(2:11)), it seems to start multiple processes, but then crashes and gives an error: KeyError: key ProgressMeter [92933f4c-e287-5a05-a399-4b506db050ca] not found

When I do the second version (Vector(1:11)), it seems to run only a single process (or at least it's engaging only one cpu core).

I am using julia 1.9.0 and GeoStats v0.39.0 on TOSS Linux (RHEL).

**Comment by juliohm** [comment] 2023-06-06 20:45
Thank you for reporting the issue @conordoherty , can you please provide a minimum working example (MWE) so that we can copy/paste and reproduce the issue ourselves?

**Comment by conordoherty** [comment] 2023-06-06 20:46
Yes sorry your last comment didn't load on zulip right away for some reason. I am working on it now and will update when ready.

**Comment by conordoherty** [comment] 2023-06-06 21:09
I haven't tested on Linux yet but on my macbook this code produces the following error: 

```
LoadError: On worker 2:
KeyError: key ProgressMeter [92933f4c-e287-5a05-a399-4b506db050ca] not found
```

The code (based on example from GeoStats docs):

```
using GeoStats, Distributed

addprocs(4)

table = (Z=[1.,0.,1.],)
coord = [(25.,25.), (50.,75.), (75.,50.)]

D = georef(table, coord)
G = CartesianGrid(100, 100)

problem = SimulationProblem(D, G, :Z, 10)
solver = SGS(:Z => (variogram=GaussianVariogram(range=35), maxneighbors=30,))
s = solve(problem, solver, procs=Vector(1:5))
```

**Comment by juliohm** [comment] 2023-06-06 21:31
@eliascarv this is very likely related to the recent addition of ProgressMeter in the `solve` fallback method.

**Comment by juliohm** [comment] 2023-06-06 21:37
@conordoherty I've ran the code locally. The issue is actually happening because you didn't import the implementation everywhere. The way the Distributed stdlib works is that you load the code on every process and execute from the main process. The following script works:

```julia
using Distributed

# request processes
addprocs(4)

# load code on every process
@everywhere using GeoStats

# main script on main process
table = (Z=[1.,0.,1.],)
coord = [(25.,25.), (50.,75.), (75.,50.)]

D = georef(table, coord)
G = CartesianGrid(100, 100)

problem = SimulationProblem(D, G, :Z, 10)
solver = SGS(:Z => (variogram=GaussianVariogram(range=35), maxneighbors=30,))

# solve on all processes
solve(problem, solver, procs=procs())
```

**Comment by juliohm** [comment] 2023-06-06 21:38
You can learn more about the distributed execution model in our ultimate guide here:

https://github.com/Arpeggeo/julia-distributed-computing

**Comment by juliohm** [comment] 2023-06-06 21:38
Closing the issue as invalid.

**Closed by juliohm** 2023-06-06 21:38 UTC
Labels: invalid
